#!/bin/bash

if [ ! -f ~/.ep128emu/roms/ep128emu_roms-2.0.10.bin ];then
  if [ -f /usr/share/ep128emu/roms/ep128emu_roms-2.0.10.bin ];then
    mkdir -p ~/.ep128emu/roms
    ( cd ~/.ep128emu/roms && epcompress -x -a /usr/share/ep128emu/roms/ep128emu_roms-2.0.10.bin )
  fi
fi
if [ ! -f ~/.ep128emu/config/ep128uk/EP_640k_EXOS24_SDEXT_utils.cfg ];then
  epmakecfg -f "$HOME/.ep128emu"
fi
exec ep128emu.bin "$@"
