#!/bin/bash

if [ ! -f ~/.ep128emu/roms/exos232uk.rom ];then
  mkdir -p ~/.ep128emu/roms
  if [ ! -f ~/.ep128emu/roms/ep128emu_roms.bin ];then
    if [ -f /usr/share/ep128emu/roms/ep128emu_roms.bin ];then
      cp /usr/share/ep128emu/roms/ep128emu_roms.bin ~/.ep128emu/roms/
    else
      curl -o "$HOME/.ep128emu/roms/ep128emu_roms.bin"        \
      "http://ep128emu.enterpriseforever.com/roms/ep128emu_roms.bin"
    fi
  epmakecfg "$HOME/.ep128emu"
  fi
fi
exec ep128emu.bin "$@"
